[package]
name = "sensors-mon"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.87"
lm-sensors = "0.3.1"
nvml-wrapper = "0.10.0"
pico-args = "0.5.0"
ratatui = "0.28.0"
